Added the option to write the measurement errors to the secondary output file
ORAC-CC/orac pull request #96
Opened 2024-03-18 12:31 UTC by garethethomas

It can be quite useful to see what values for measurement error are actually being used in the retrieval, so this adds the option to request the diagonals of the Sy covariance matrix be output to the seondary.nc file.

2024-03-21 17:18 UTC, adamcpovey requested changes
I'll make some whitespace tidying and work out the channel indexing

2024-03-21 17:18 UTC, adamcpovey commented on src/get_spixel.F90
> +   if (SPixel%Ind%Ny == 0) then
While I'm not surprised this is possible, someone should track down what the failure mode is and fix that too.

2024-03-21 17:18 UTC, adamcpovey commented on src/prepare_output_secondary.F90
> +                 sqrt(SPixel%Sy(k,k)), output_data%Sy(i,j,k), &
This doesn't map channels between SPixel and Ctrl and so is outputting in the wrong place. I'll work out a fix momentarily.

2024-03-21 18:47 UTC, adamcpovey commented
After 20 minutes I worked out how to push changes to your branch and update this thing! @garethethomas please check that those still address the problems you were having (I went looking for the causes of the missed status flag rather than circumvent the whole system).

Further, I am beginning to question a bunch of stuff in here:

- Why are we allocating SPixel arrays each time when they just get copied into local arrays in `invert_marquadt()`? We probably save a bunch of processing time by not bothering to reallocate.
- Given the output arrays are initialised to fill values, why do we call `prepare_output_XXX()` for skipped retrievals? Surely doing nothing outputs what we want (namely nothing)?

2024-04-11 11:16 UTC, garethethomas commented
I agree with your inclusion of `SPixel%spixel_y_to_ctrl_y_index` - from what I've seen it isn't generally necessary (it's a one-to-one match), but I guess this might not _always_ be the case!
Regarding your other change - it _should_ be ok, so long as `SPixel%Ny = 0` means that the do loop at line 338 of prepare_output_secondary.F90  doesn't get executed. Is that how Fortran works?

I was also surprised at the fact that all of the SPixel arrays are reallocated for every pixel - like you say, it seems rather inefficient. "Fixing" this would be a big job though!

2024-04-11 13:28 UTC, adamcpovey commented
`SPixel%spixel_y_to_ctrl_y_index` is mostly important for the cloud retrieval, as one of the effective radius channels is _always_ missing when multiple are present.

To my knowledge, Fortran checks the validity of the for condition at the start of the loop so `do i=1,0` should immediately terminate.

2024-04-18 08:32 UTC, adamcpovey commented
I never managed to work out how to get sensible errors out of flex. You can get it to at least throw a line number and slightly more information (almost always "syntax", but others can happen) by uncommenting the last two lines of `config/arch.inc`

2024-04-18 08:33 UTC, merged